language: php

services: mongodb

php:
  - 5.3
  - 5.4
  - 5.5
before_script:
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - wget https://github.com/downloads/Behat/Behat/behat.phar
    - curl https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.6.0 DEBUG=1 bash


script:
    - phpunit
    - php behat.phar
#notifications:
#  email:
#    - fsemm.travis-ci@gmx.de
